# Generated by Django 2.1.7 on 2019-03-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20190302_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/default_img/default.png', upload_to='products_images'),
        ),
    ]
