# Generated by Django 2.1.7 on 2019-03-02 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_auto_20190302_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='/products_images/default.png', upload_to='products_images'),
        ),
    ]
