# Generated by Django 2.1.7 on 2019-03-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0010_auto_20190302_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='trending',
            field=models.BooleanField(blank=True, default=True, verbose_name='Тренд'),
        ),
    ]
