# Generated by Django 2.1.7 on 2019-03-18 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='number',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='price_per_item',
        ),
        migrations.RemoveField(
            model_name='productinorder',
            name='total_price',
        ),
        migrations.AddField(
            model_name='productinorder',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
